blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/JamesPagetButler/QBP/tree/master/docs
    about: Check the documentation before opening an issue
  - name: Issue Schema
    url: https://github.com/JamesPagetButler/QBP/blob/master/docs/schemas/issue_schema.md
    about: Review issue best practices and schema
